version: "3.5"

services:
  db:
    image: mariadb:10.2
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=matomo"
      - "MYSQL_USER=matomo"
      - "MYSQL_PASSWORD=asupersecretpassword"
    networks:
      - internal
    labels:
      - "traefik.enable=false"
    restart: always

  redis:
    image: redis:4.0-alpine
    networks:
      - internal
    labels:
      - "traefik.enable=false"
    restart: always

  msmtpd:
    image: crazymax/msmtpd:latest
    env_file:
      - "./msmtpd.env"
    environment:
      - "TZ"
    networks:
      - internal
    labels:
      - "traefik.enable=false"
    restart: always

  geoip-updater:
    image: crazymax/geoip-updater:latest
    volumes:
      - "./geoip-updater:/data"
    env_file:
      - "./geoip-updater.env"
    environment:
      - "TZ"
    networks:
      - internal
    labels:
      - "traefik.enable=false"
    restart: always

  matomo:
    image: crazymax/matomo:latest
    depends_on:
      - db
      - redis
      - msmtpd
    volumes:
      - "./matomo:/data"
      - "./geoip-updater:/data/geoip"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.matomo.entrypoints=websecure"
      - "traefik.http.routers.matomo.rule=Host(`matomo.mgmt.sbob.uk`)"
      - "traefik.http.routers.matomo.tls=true"
      - "traefik.http.routers.matomo.tls.certresolver=leresolver"
      - "traefik.http.routers.matomo.tls.domains[0].main=matomo.mgmt.sbob.uk"
      - "traefik.http.services.matomo.loadbalancer.server.port=8000"
    env_file:
      - "./matomo.env"
    environment:
      - "TZ"
    networks:
      - internal
      - web
    restart: always

  cron:
    image: crazymax/matomo:latest
    depends_on:
      - matomo
    volumes:
      - "./matomo:/data"
      - "./geoip-updater:/data/geoip"
    env_file:
      - "./matomo.env"
    environment:
      - "TZ"
      - "SIDECAR_CRON=1"
      - "CRON_ARCHIVE=0 * * * *"
      - "ARCHIVE_OPTIONS=--concurrent-requests-per-website=3"
    healthcheck:
      disable: true
    networks:
      - internal
    labels:
      - "traefik.enable=false"
    restart: always

networks:
  web:
    external:
      name: web
  internal:
